[font]
size = 11

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[font.bold]
family = "DejaVu Sans Mono"
style = "Bold"

[font.bold_italic]
family = "DejaVu Sans Mono"
style = "Bold Italic"

[font.italic]
family = "DejaVu Sans Mono"
style = "Italic"

[colors.primary]
background = "#080808"
